# 通用配置
server:
  port: 8004
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flag?useUnicode=true&amp;characterEncoding=UTF-8
    username: flag
    password: flag
## 微信openid配置
wx:
  appid: wx2f6e3eb2fb0cc937
  secret: fd42347bdb8152a8d426a58960e34e9f
  url: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&grant_type=authorization_code&js_code=

---
# 开发环境配置
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
      restart:
        enabled: true
logging:
  level:
    org.springframework.web: warn
    com.ctg: warn
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
  file: /www/wwwlogs/flag.log

---
# 线上环境配置
spring:
  profiles: pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  devtools:
    restart:
      enabled: false
logging:
  level:
    root: error
    org.springframework.web: error
    com.ctg: error
  pattern:
    console:
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
  file: /www/wwwlogs/flag.log
