spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flag?characterEncoding=utf-8
    username: flag
    password: flag
mybatis:
  type-aliases-package: com.ctg.flag.pojo.entity
